# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7587cb73dcda9964de1117b5f1d3721a93993491767955d8cb80d9a01e5c21d9a172f97fe1eddd7e2ddda28dd69dd68f5c2aa069adb85a7152ef30485f77ab43

test:
  secret_key_base: 0fd35034544299764fc76fae48495f6d8f279b33d211f00bbc6f42f97c15ef2b37e3197c2d46305a468f9589a1795ab8b5351ee1cc2f377541e2c8ffe79a08e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
